export enum OrderRolProperty {
	name = 'name',
	permissions = 'permissions',
	typeRol = 'typeRol',
}

export const textOrderRol = {
	name: 'Nombre',
	permissions: 'Permisos',
	typeRol: 'Tipo de Rol',
};

export enum RolType {
	admin = 'admin',
	user = 'user',
}
export const RolTypeText = {
	admin: 'Administrador',
	user: 'Usuario',
};

export enum Permission {
	super = 'SUPER',
	user = 'USER',
	userProfile = 'USER_PROFILE',
	userAdd = 'USER_ADD',
	userRead = 'USER_READ',
	userReadOne = 'USER_READ_ONE',
	userUpdate = 'USER_UPDATE',
	userDelete = 'USER_DELETE',
	rol = 'ROL',
	rolAdd = 'ROL_ADD',
	rolRead = 'ROL_READ',
	rolReadOne = 'ROL_READ_ONE',
	rolUpdate = 'ROL_UPDATE',
	rolDelete = 'ROL_DELETE',
	pathology = 'PATHOLOGY',
	pathologyAdd = 'PATHOLOGY_ADD',
	pathologyRead = 'PATHOLOGY_READ',
	pathologyReadOne = 'PATHOLOGY_READ_ONE',
	pathologyUpdate = 'PATHOLOGY_UPDATE',
	pathologyDelete = 'PATHOLOGY_DELETE',
	medicament = 'MEDICAMENT',
	medicamentAdd = 'MEDICAMENT_ADD',
	medicamentRead = 'MEDICAMENT_READ',
	medicamentReadOne = 'MEDICAMENT_READ_ONE',
	medicamentUpdate = 'MEDICAMENT_UPDATE',
	medicamentDelete = 'MEDICAMENT_DELETE',
	medicationRequest = 'MEDICATIONREQUEST',
	medicationRequestAdd = 'MEDICATIONREQUEST_ADD',
	medicationRequestRead = 'MEDICATIONREQUEST_READ',
	medicationRequestReadOne = 'MEDICATIONREQUEST_READ_ONE',
	medicationRequestUpdate = 'MEDICATIONREQUEST_UPDATE',
	medicationRequestAssign = 'MEDICATIONREQUEST_ASSIGN',
	medicationRequestDeliveryData = 'MEDICATIONREQUEST_DELIVERY_DATA',
	medicationRequestDelete = 'MEDICATIONREQUEST_DELETE',
	medicationRequestPharmacy = 'MEDICATIONREQUEST_PHARMACY',
	medicationRequestValidatePatient = 'MEDICATIONREQUEST_VALIDATE_PATIENT',
	pharmacy = 'PHARMACY',
	pharmacyAdd = 'PHARMACY_ADD',
	pharmacyRead = 'PHARMACY_READ',
	pharmacyReadOne = 'PHARMACY_READ_ONE',
	pharmacyUpdate = 'PHARMACY_UPDATE',
	pharmacyDelete = 'PHARMACY_DELETE',
	patient = 'PATIENTS',
	patientAdd = 'PATIENTS_ADD',
	patientRead = 'PATIENTS_READ',
	patientReadOne = 'PATIENTS_READ_ONE',
	patientUpdate = 'PATIENTS_UPDATE',
	patientDelete = 'PATIENTS_DELETE',
	deliveryData = 'DELIVERYDATA',
	deliveryDataAdd = 'DELIVERYDATA_ADD',
	deliveryDataRead = 'DELIVERYDATA_READ',
	deliveryDataReadOne = 'DELIVERYDATA_READ_ONE',
	deliveryDataUpdate = 'DELIVERYDATA_UPDATE',
	deliveryDataDelete = 'DELIVERYDATA_DELETE',
	inventory = 'INVENTORY',
	inventoryAdd = 'INVENTORY_ADD',
	inventoryRead = 'INVENTORY_READ',
	inventoryReadOne = 'INVENTORY_READ_ONE',
	inventoryUpdate = 'INVENTORY_UPDATE',
	inventoryDelete = 'INVENTORY_DELETE',
	assignation = 'ASSIGNATION',
	assignationAdd = 'ASSIGNATION_ADD',
	assignationRead = 'ASSIGNATION_READ',
	assignationReadOne = 'ASSIGNATION_READ_ONE',
	assignationUpdate = 'ASSIGNATION_UPDATE',
	assignationDelete = 'ASSIGNATION_DELETE',
	assignationPDF = 'ASSIGNATION_PDF',
	incidentReport = 'INCIDENTREPORT',
	incidentReportAdd = 'INCIDENTREPORT_ADD',
	incidentReportRead = 'INCIDENTREPORT_READ',
	incidentReportReadOne = 'INCIDENTREPORT_READ_ONE',
	incidentReportUpdate = 'INCIDENTREPORT_UPDATE',
	incidentReportDelete = 'INCIDENTREPORT_DELETE',
	incidentReportUpdateStatus = 'INCIDENTREPORT_UPDATE_STATUS',
}

export const permissionTranslations = {
	SUPER: 'Super Usuario',
	USER: 'Usuario',
	USER_PROFILE: 'Perfil de Usuario',
	USER_ADD: 'Agregar Usuario',
	USER_READ: 'Leer Usuario',
	USER_READ_ONE: 'Leer Un Usuario',
	USER_UPDATE: 'Actualizar Usuario',
	USER_DELETE: 'Eliminar Usuario',
	ROL: 'Rol',
	ROL_ADD: 'Agregar Rol',
	ROL_READ: 'Leer Rol',
	ROL_READ_ONE: 'Leer Un Rol',
	ROL_UPDATE: 'Actualizar Rol',
	ROL_DELETE: 'Eliminar Rol',
	PATHOLOGY: 'Patología',
	PATHOLOGY_ADD: 'Agregar Patología',
	PATHOLOGY_READ: 'Leer Patología',
	PATHOLOGY_READ_ONE: 'Leer Una Patología',
	PATHOLOGY_UPDATE: 'Actualizar Patología',
	PATHOLOGY_DELETE: 'Eliminar Patología',
	MEDICAMENT: 'Medicamento',
	MEDICAMENT_ADD: 'Agregar Medicamento',
	MEDICAMENT_READ: 'Leer Medicamento',
	MEDICAMENT_READ_ONE: 'Leer Un Medicamento',
	MEDICAMENT_UPDATE: 'Actualizar Medicamento',
	MEDICAMENT_DELETE: 'Eliminar Medicamento',
	MEDICATIONREQUEST: 'Solicitud de Medicación',
	MEDICATIONREQUEST_ADD: 'Agregar Solicitud de Medicación',
	MEDICATIONREQUEST_READ: 'Leer Solicitud de Medicación',
	MEDICATIONREQUEST_READ_ONE: 'Leer Una Solicitud de Medicación',
	MEDICATIONREQUEST_UPDATE: 'Actualizar Solicitud de Medicación',
	MEDICATIONREQUEST_DELETE: 'Eliminar Solicitud de Medicación',
	MEDICATIONREQUEST_PHARMACY: 'Solicitud de Medicación Seleción de Farmacia',
	MEDICATIONREQUEST_VALIDATE_PATIENT: 'Validar Paciente',
	PHARMACY: 'Farmacia',
	PHARMACY_ADD: 'Agregar Farmacia',
	PHARMACY_READ: 'Leer Farmacia',
	PHARMACY_READ_ONE: 'Leer Una Farmacia',
	PHARMACY_UPDATE: 'Actualizar Farmacia',
	PHARMACY_DELETE: 'Eliminar Farmacia',
	PATIENTS: 'Pacientes',
	PATIENTS_ADD: 'Agregar Paciente',
	PATIENTS_READ: 'Leer Paciente',
	PATIENTS_READ_ONE: 'Leer Un Paciente',
	PATIENTS_UPDATE: 'Actualizar Paciente',
	PATIENTS_DELETE: 'Eliminar Paciente',
	DELIVERYDATA: 'Datos de Entrega',
	DELIVERYDATA_ADD: 'Agregar Datos de Entrega',
	DELIVERYDATA_READ: 'Leer Datos de Entrega',
	DELIVERYDATA_READ_ONE: 'Leer Unos Datos de Entrega',
	DELIVERYDATA_UPDATE: 'Actualizar Datos de Entrega',
	DELIVERYDATA_DELETE: 'Eliminar Datos de Entrega',
	INVENTORY: 'Inventario',
	INVENTORY_ADD: 'Agregar Inventario',
	INVENTORY_READ: 'Leer Inventario',
	INVENTORY_READ_ONE: 'Leer un dato de inventario',
	INVENTORY_UPDATE: 'Actualizar dato de invetario',
	INVENTORY_DELETE: 'Eliminar dato de inventario',
	ASSIGNATION: 'Asignación',
	ASSIGNATION_ADD: 'Agregar Asignación',
	ASSIGNATION_READ: 'Leer Asignación',
	ASSIGNATION_READ_ONE: 'Leer Una Asignación',
	ASSIGNATION_UPDATE: 'Actualizar Asignación',
	ASSIGNATION_DELETE: 'Eliminar Asignación',
	ASSIGNATION_PDF: 'PDF',
	INCIDENTREPORT: 'Reporte de Incidente',
	INCIDENTREPORT_ADD: 'Agregar Reporte de Incidente',
	INCIDENTREPORT_READ: 'Leer Reporte de Incidente',
	INCIDENTREPORT_READ_ONE: 'Leer Un Reporte de Incidente',
	INCIDENTREPORT_UPDATE: 'Actualizar Reporte de Incidente',
	INCIDENTREPORT_DELETE: 'Eliminar Reporte de Incidente',
	INCIDENTREPORT_UPDATE_STATUS: 'Actualizar Estado de Reporte de Incidente',
};
